#!/bin/sh

bars="$(nmcli dev wifi list | awk '/\*/{if (NR!=1) {print $9}}')"

symbol() {
[ $(cat /sys/class/net/w*/operstate) = down ] && echo 󰤮 && exit

if [ $bars = ▂▄▆█ ]; then
  echo 󰤨
elif [ $bars = ▂▄▆_ ]; then
  echo 󰤥
elif [ $bars = ▂▄__ ]; then
  echo 󰤢 
elif [ $bars = ▂___ ]; then
  echo 󰤟
else
  echo 󰤯
fi
  
}

name() {
nmcli | grep "^wlp" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
