#!/bin/sh

bars="$(nmcli dev wifi list | awk '/\*/{if (NR!=1) {print $8}}')"

symbol() {
[ $(cat /sys/class/net/w*/operstate) = down ] && echo 󰤮 && exit

if [ $bars -gt 80 ]; then
  echo 󰤨
    
elif [ $bars -gt 60 ]; then
  echo 󰤥

elif [ $bars -gt 40 ]; then
  echo 󰤢 

elif [ $bars -gt 20 ]; then
  echo 󰤟
    
else
  echo 󰤯

fi
  
}

name() {
nmcli | grep "^wlp" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
