format = """
[░▒▓](#95e5cb)\
[  ](bg:#95e5cb fg:#0e1419)\
$env_var\
[](bg:#c7fffc fg:#95e5cb)\
$username\
$hostname\
[](fg:#c7fffc bg:#0e1419)\
$line_break\
[░▒▓](#ff6565)\
$git_branch\
$git_status\
[ ](fg:#ff6565 bg:#ffa3aa)\
[ ](fg:#ffa3aa bg:#394260)\
$directory\
[](fg:#394260 bg:#212736)\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#CBBAED bg:#394260"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "Documents"
"Downloads" = "Downloads"
"Music" = "Music"
"Pictures" = "Pictures"

[username]
style_user = 'fg:bold #2B3D41 bg:#c7fffc'
style_root = 'fg:bold red bg:#c7fffc'
format = '[ $user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@$hostname](fg:bold #F07078 bg:#c7fffc)'
disabled = false

[env_var]
variable = 'CONDA_DEFAULT_ENV'
format = "[ {$env_value} ](fg:#090c0c bg:#95e5cb)"
disabled = false
default = '~'

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#323232 bg:#ff6565)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#323232 bg:#ff6565)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

