[theme]
background = "#394260"
primary = "#A0A9CB"
secondary = "#CBBAED"
title = "#8FD6C9"
playing = "#DE3C4B"
playing_selected = "#8FD6C9"
playing_bg = "#1D2230"
highlight = "#1D2230"
highlight_bg = "#8FD6C9"
error = "#FFFFFF"
error_bg = "#A50000"
statusbar = "#394260"
statusbar_progress = "#8FD6C9"
statusbar_bg = "#8FD6C9"
cmdline = "#A0A9CB"
cmdline_bg = "#394260"
