#!/bin/sh

# Check current theme
export STATUS_FILE="/home/daraghhollman/.config/waybar/theme.status"

#if the theme is not dark then we need to switch to it
if [[ $(cat $STATUS_FILE) == "light" ]]; then
    SWITCHTO="-dark"
    MODESTR="Dark"
    printf "dark" > "$STATUS_FILE"
else
    SWITCHTO=""
    MODESTR="Light"
    printf "light" > "$STATUS_FILE"
fi

echo "$SWTICHTO"
echo "$MODSTR"

#show a message
notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to $MODESTR"

# Change theme 
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"

#change the background image
feh --bg-scale ~/Photos/Wallpapers/'background'$SWITCHTO.jpg

if [[ $MODESTR == "Light" ]]; then
    cp /home/daraghhollman/hyprlock-light.conf /home/daraghhollman/hyprlock.conf

else
    cp /home/daraghhollman/hyprlock-dark.conf /home/daraghhollman/hyprlock.conf

# restart bar
pkill polybar
polybar &
