#!/usr/bin/env bash

## Generic bemenu script. Will be run from other scripts to make sure, bemenu always looks the same

background='#0e1419'
color5='#95e5cb'

BEMENU_ARGS=(-n -i -p '' --tb "$background" --tf "$color5" --fb "$background" --nb "$background" --ab "$background" --hb "$background" --hf "$color5" --line-height 30 "$@")

if [ "$1" = 'dmenu' ]; then
  bemenu-run "${BEMENU_ARGS[@]}"
else
  bemenu "${BEMENU_ARGS[@]}"
fi
